import type { Base64File, DropdownInterface } from "./AtsCommonInterface";

export interface EducationData {
	institute?: string;
	major: string;
	degree: string;
	currentlyPursuing: boolean;
	startDate: Date | string;
	endDate: Date | string | null;
	[key: string]: unknown;
}

export interface ExperienceData {
	occupationTitle: string;
	company: string;
	summary: string;
	startDate: Date | string;
	endDate: Date | string | null;
	currentlyWorkingHere: boolean;
	[key: string]: unknown;
}

interface SalaryAnnexureInterface {
	monthlyInputValue?: number;
	annualCtcWords?: number;
	basicMonthly?: number;
	basicAnnually?: number;
	houseRentAllowanceMonthly?: number;
	houseRentAllowanceAnnually?: number;
	conveyanceAllowanceMonthly?: number;
	conveyanceAllowanceAnnually?: number;
	attireExpensesMonthly?: number;
	attireExpensesAnnually?: number;
	medicalAllowanceMonthly?: number;
	medicalAllowanceAnnually?: number;
	leaveTravelAllowanceMonthly?: number;
	leaveTravelAllowanceAnnually?: number;
	profPersuitExpenseMonthly?: number;
	profPersuitExpenseAnnually?: number;
	statutoryBonusMonthly?: number;
	statutoryBonusAnnually?: number;
	fixedAllowanceMonthly?: number;
	fixedAllowanceAnnually?: number;
	totalGrossMonthly?: number;
	totalGrossAnnually?: number;
	gratuityEmployerContributionMonthly?: number;
	gratuityEmployerContributionAnnually?: number;
	groupHealthInsuranceEmployerContributionMonthly?: number;
	groupHealthInsuranceEmployerContributionAnnually?: number;
	epfEmployerContributionMonthly?: number;
	epfEmployerContributionAnnually?: number;
	totalRetiralMonthly?: number;
	totalRetiralAnnually?: number;
	costToCompanyMonthly?: number;
	costToCompanyAnnually?: number;
	createdDate?: string;
	updatedDate?: string;
}

export interface CandidateInterface {
	candidateId?: number;
	firstName?: string;
	lastName?: string;
	email?: string;
	mobile?: string;
	phone?: string;
	fax?: string;
	createdBy?: number;
	website?: string;
	secondaryEmail?: string;
	currencyId?: number;
	street?: string;
	city?: string;
	province?: string;
	countryId?: number;
	postalCode?: string;
	experience?: number;
	qualificationId?: number;
	relevantExperience?: number;
	currentEmployer?: string;
	currentCtc?: number;
	currentSalary?: number;
	expectedCtc?: number;
	isAlreadyAnApplicant?: boolean;
	currentJobTitle?: string;
	noticePeriodDays?: number;
	alternateOffer?: string;
	currentLocation?: string;
	willingToWorkInTrivandrum?: boolean;
	expectedSalaryId?: number;
	expectedSalaryDetails?: DropdownInterface;
	expectedDOJ?: string;
	deletedDate?: string;
	createdDate?: string;
	skypeId?: string;
	skillSet?: Array<string>;
	candidateStatusId?: number;
	sourceId?: number;
	candidateOwnerId?: number;
	emailOptOut?: boolean;
	monthlyInputValue?: number;
	annualCtcWords?: number;
	basicMonthly?: number;
	basicAnnually?: number;
	houseRentAllowanceMonthly?: number;
	houseRentAllowanceAnnually?: number;
	conveyanceAllowanceMonthly?: number;
	conveyanceAllowanceAnnually?: number;
	attireExpensesMonthly?: number;
	attireExpensesAnnually?: number;
	medicalAllowanceMonthly?: number;
	medicalAllowanceAnnually?: number;
	leaveTravelAllowanceMonthly?: number;
	leaveTravelAllowanceAnnually?: number;
	profPersuitExpenseMonthly?: number;
	profPersuitExpenseAnnually?: number;
	statutoryBonusMonthly?: number;
	statutoryBonusAnnually?: number;
	fixedAllowanceMonthly?: number;
	fixedAllowanceAnnually?: number;
	totalGrossMonthly?: number;
	totalGrossAnnually?: number;
	gratuityEmployerContributionMonthly?: number;
	gratuityEmployerContributionAnnually?: number;
	groupHealthInsuranceEmployerContributionMonthly?: number;
	groupHealthInsuranceEmployerContributionAnnually?: number;
	epfEmployerContributionMonthly?: number;
	epfEmployerContributionAnnually?: number;
	totalRetiralMonthly?: number;
	totalRetiralAnnually?: number;
	costToCompanyMonthly?: number;
	costToCompanyAnnually?: number;
	updatedDate?: string;
	linkedin?: string;
	facebook?: string;
	resumeFile?: Base64File[];
	coverLetterUpload?: Base64File[];
	contractUpload?: Base64File[];
	otherFiles?: Base64File[];
	status?: DropdownInterface;
	candidateOwnerDetails?: DropdownInterface;
	countryDetails?: DropdownInterface;
	currencyDetails?: DropdownInterface;
	qualificationDetails?: DropdownInterface;
	salaryAnnexure?: SalaryAnnexureInterface;
	professionalDetails?: ExperienceData[];
	educationalDetails?: EducationData[];
	candidateStatusDetails?: DropdownInterface;
	sourceDetails?: DropdownInterface;
	jobPosition?: DropdownInterface;
	candidateStage?: DropdownInterface;
	documents?: Base64File[];
	jobOpportunityId?: number;
	aiResumeMatchScore?: number;
	jobOpportunity?: DropdownInterface;
	[key: string]: unknown;
}
