trigger:
- develop

variables:
- group: pats_fe

pool:
  name: 'PATS'

stages:
- stage: QualityTest
  displayName: "Quality Test"
  jobs:
  - job: Scanning
    displayName: "Quality Test Scanning"
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 5
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'PATS_FE'
        cliProjectName: 'PATS_FE'
        cliSources: '.'

    - task: SonarQubeAnalyze@5

#    - task: SonarQubePublish@5
#      inputs:
#        pollingTimeoutSec: '300'

    - task: sonar-buildbreaker@8
      inputs:
        SonarQube: 'SonarQube'

- stage: Build
  displayName: 'Docker Build'
  jobs:
  - job: Build
    displayName: 'Build and Push Docker Images'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker_Pits'
        repository: '$(dockerrepo)'
        command: 'build'
        Dockerfile: 'Dockerfile'

    - task: Docker@2
      inputs:
        containerRegistry: 'Docker_Pits'
        repository: '$(dockerrepo)'
        command: 'push'
